apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xt-tickets
  template:
    metadata:
      labels:
        app: xt-tickets
    spec:
      containers:
        - name: xt-tickets
          image: guyberko/xt-tickets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/xt-tickets'
            - name: PORT
              value: '3000'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'xtickets'
            - name: NODE_ENV
              value: 'development'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: xt-tickets
  ports:
    - name: xt-tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
