apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xt-expiration
  template:
    metadata:
      labels:
        app: xt-expiration
    spec:
      containers:
        - name: xt-expiration
          image: guyberko/xt-expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'xtickets'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
