name: deploy-manifests

on: 
  push:
    branches: 
      - main
    paths:
      - 'xt-infra/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save xtickets
      - run: kubectl apply -f xt-infra/k8s
