name: Tests-Auth

on:
  pull_request:
    paths:
      - 'xt-auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd xt-auth && npm i && npm run test:ci
