name: Tests-Payments

on:
  pull_request:
    paths:
      - 'xt-payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd xt-payments && npm i && npm run test:ci
