name: Tests-Orders

on:
  pull_request:
    paths:
      - 'xt-orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd xt-orders && npm i && npm run test:ci
